CREATE ROLE [db_schema_SASTEMP_SUID]
AUTHORIZATION [dbo]
GO
EXEC sp_addrolemember N'db_schema_SASTEMP_SUID', N'svc_saslimitschema'
GO
GRANT CREATE FUNCTION TO [db_schema_SASTEMP_SUID]
GRANT CREATE PROCEDURE TO [db_schema_SASTEMP_SUID]
GRANT CREATE TABLE TO [db_schema_SASTEMP_SUID]
GRANT CREATE VIEW TO [db_schema_SASTEMP_SUID]
