SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[vw_CD_DimCustomer] AS     
    
SELECT    
	b.DimCustomerId    
	,a.BatchId    
	,b.ODSRowLastUpdated    
	,b.SourceDB    
	,a.SourceSystem    
	,b.SourceSystemPriority    
	,a.SSID    
	,b.CustomerType    
	,b.CustomerStatus    
	,b.customer_matchkey    
	,b.matchkey_updatedate    
	,b.AccountId    
	,b.AccountType    
	,b.AccountRep    
	,a.CompanyName    
	,a.CompanyNameIsCleanStatus  
	,b.SalutationName    
	,b.DonorMailName    
	,b.DonorFormalName    
	,b.Birthday    
	,a.Gender    
	,b.CD_Gender    
	,b.MergedRecordFlag    
	,b.MergedIntoSSID    
	,b.IsBusiness    
	,b.contactattrDirtyHash    
	,a.Prefix    
	,a.FirstName    
	,a.MiddleName    
	,a.LastName    
	,a.Suffix    
	,a.FullName    
	,b.NameDirtyHash    
	,a.NameIsCleanStatus    
	,b.NameMasterId    
	,a.AddressPrimaryStreet    
	,a.AddressPrimarySuite    
	,a.AddressPrimaryCity    
	,a.AddressPrimaryState    
	,a.AddressPrimaryZip    
	,a.AddressPrimaryPlus4    
	,a.AddressPrimaryCounty    
	,a.AddressPrimaryCountry    
	,a.AddressPrimaryLatitude    
	,a.AddressPrimaryLongitude    
	,b.AddressPrimaryDirtyHash    
	,a.AddressPrimaryIsCleanStatus    
	,a.AddressPrimaryNCOAStatus    
	,b.AddressPrimaryMasterId    
	,b.ContactDirtyHash    
	,a.ContactGUID    
	,a.AddressOneStreet    
	,a.AddressOneSuite    
	,a.AddressOneCity    
	,a.AddressOneState    
	,a.AddressOneZip    
	,a.AddressOnePlus4    
	,a.AddressOneCounty    
	,a.AddressOneCountry    
	,a.AddressOneLatitude    
	,a.AddressOneLongitude    
	,b.AddressOneDirtyHash    
	,a.AddressOneIsCleanStatus    
	,a.AddressOneStreetNCOAStatus    
	,b.AddressOneMasterId    
	,a.AddressTwoStreet    
	,a.AddressTwoSuite    
	,a.AddressTwoCity    
	,a.AddressTwoState    
	,a.AddressTwoZip    
	,a.AddressTwoPlus4    
	,a.AddressTwoCounty    
	,a.AddressTwoCountry    
	,a.AddressTwoLatitude    
	,a.AddressTwoLongitude    
	,b.AddressTwoDirtyHash    
	,a.AddressTwoIsCleanStatus    
	,a.AddressTwoStreetNCOAStatus    
	,b.AddressTwoMasterId    
	,a.AddressThreeStreet    
	,a.AddressThreeSuite    
	,a.AddressThreeCity    
	,a.AddressThreeState    
	,a.AddressThreeZip    
	,a.AddressThreePlus4    
	,a.AddressThreeCounty    
	,a.AddressThreeCountry    
	,a.AddressThreeLatitude    
	,a.AddressThreeLongitude    
	,b.AddressThreeDirtyHash    
	,a.AddressThreeIsCleanStatus    
	,a.AddressThreeStreetNCOAStatus    
	,b.AddressThreeMasterId    
	,a.AddressFourStreet    
	,a.AddressFourSuite    
	,a.AddressFourCity    
	,a.AddressFourState    
	,a.AddressFourZip    
	,a.AddressFourPlus4    
	,a.AddressFourCounty    
	,a.AddressFourCountry    
	,a.AddressFourLatitude    
	,a.AddressFourLongitude    
	,b.AddressFourDirtyHash    
	,a.AddressFourIsCleanStatus    
	,a.AddressFourStreetNCOAStatus    
	,b.AddressFourMasterId    
	,a.PhonePrimary    
	,b.PhonePrimaryDNC    
	,b.PhonePrimaryDirtyHash    
	,a.PhonePrimaryIsCleanStatus    
	,b.PhonePrimaryMasterId    
	,a.PhoneHome    
	,b.PhoneHomeDNC    
	,b.PhoneHomeDirtyHash    
	,a.PhoneHomeIsCleanStatus    
	,b.PhoneHomeMasterId    
	,a.PhoneCell    
	,b.PhoneCellDNC    
	,b.PhoneCellDirtyHash    
	,a.PhoneCellIsCleanStatus    
	,b.PhoneCellMasterId    
	,a.PhoneBusiness    
	,b.PhoneBusinessDNC    
	,b.PhoneBusinessDirtyHash    
	,a.PhoneBusinessIsCleanStatus    
	,b.PhoneBusinessMasterId    
	,a.PhoneFax    
	,b.PhoneFaxDNC    
	,b.PhoneFaxDirtyHash    
	,a.PhoneFaxIsCleanStatus    
	,b.PhoneFaxMasterId    
	,a.PhoneOther    
	,b.PhoneOtherDNC    
	,b.PhoneOtherDirtyHash    
	,a.PhoneOtherIsCleanStatus    
	,b.PhoneOtherMasterId    
	,a.EmailPrimary    
	,b.EmailPrimaryDirtyHash    
	,a.EmailPrimaryIsCleanStatus    
	,b.EmailPrimaryMasterId    
	,a.EmailOne    
	,b.EmailOneDirtyHash    
	,a.EmailOneIsCleanStatus    
	,b.EmailOneMasterId    
	,a.EmailTwo    
	,b.EmailTwoDirtyHash    
	,a.EmailTwoIsCleanStatus    
	,b.EmailTwoMasterId    
	,b.ExtAttribute1    
	,b.ExtAttribute2    
	,b.ExtAttribute3    
	,b.ExtAttribute4    
	,b.ExtAttribute5    
	,b.ExtAttribute6    
	,b.ExtAttribute7    
	,b.ExtAttribute8    
	,b.ExtAttribute9    
	,b.ExtAttribute10    
	,b.extattr1_10DirtyHash    
	,b.ExtAttribute11    
	,b.ExtAttribute12    
	,b.ExtAttribute13    
	,b.ExtAttribute14    
	,b.ExtAttribute15    
	,b.ExtAttribute16    
	,b.ExtAttribute17    
	,b.ExtAttribute18    
	,b.ExtAttribute19    
	,b.ExtAttribute20    
	,b.extattr11_20DirtyHash    
	,b.ExtAttribute21    
	,b.ExtAttribute22    
	,b.ExtAttribute23    
	,b.ExtAttribute24    
	,b.ExtAttribute25    
	,b.ExtAttribute26    
	,b.ExtAttribute27    
	,b.ExtAttribute28    
	,b.ExtAttribute29    
	,b.ExtAttribute30    
	,b.extattr21_30DirtyHash    
	,b.ExtAttribute31    
	,b.ExtAttribute32    
	,b.ExtAttribute33    
	,b.ExtAttribute34    
	,b.ExtAttribute35    
	,b.extattr31_35DirtyHash    
	,b.SSCreatedBy    
	,b.SSUpdatedBy    
	,b.SSCreatedDate    
	,b.SSUpdatedDate    
	,b.CreatedBy    
	,b.UpdatedBy    
	,a.CreatedDate    
	,a.UpdatedDate    
	,b.IsDeleted    
	,b.DeleteDate    
	,a.FuzzyNameGUID    
FROM dbo.CD_DimCustomer a    
INNER JOIN dbo.DimCustomer b ON a.SSID = b.SSID    
	AND a.SourceSystem = b.SourceSystem  
  
  
  
GO
