SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [sas].[vw_DimCustomer]
WITH SCHEMABINDING
AS
    SELECT  c.SSB_CRMSYSTEM_CONTACT_ID,
			a.DimCustomerId ,
            a.SourceDB ,
            a.SourceSystem ,
            a.SSID ,
            a.CustomerType ,
            --a.CustomerStatus ,
			CASE WHEN a.SourceSystem LIKE 'Neulion%' THEN 
						CASE WHEN a.CustomerType IN ('Active Group Member', 'Active Member', 'Active Student Ram', 'Active No Benefits', 'Active - Complementary') THEN 'Active Member'
							WHEN a.CustomerType = 'Active Group Account' THEN 'Active Group'
							WHEN a.CustomerType IN ('Deliquent Downgrade', 'Delinquent', 'Delinquent Group Account', 'Delinquent Group Member') THEN 'Delinquent Member'
							WHEN a.CustomerType IN ('Account suspended for benefit rights', 'Inactive member') THEN 'Inactive Member'
							WHEN a.CustomerType = 'Deceased Member' THEN 'Deceased Member'
							WHEN a.CustomerType IN ('ClosedAccount - Historical', 'Duplicate', 'Former Group Account-Closed', 'Former Group Mem Acct - Closed') THEN 'Closed'
							ELSE 'Not Member'
							END
					ELSE a.CustomerStatus
					END AS CustomerStatus,
            a.CompanyName ,
            a.Birthday ,
            a.Gender ,
            a.Prefix AS Prefix ,
            a.FirstName AS FirstName ,
            a.MiddleName AS MiddleName ,
            a.LastName AS LastName ,
            a.Suffix AS Suffix ,
			a.NameIsCleanStatus,
            a.AddressPrimaryStreet ,
			a.AddressPrimarySuite,
            a.AddressPrimaryCity ,
            a.AddressPrimaryState ,
            a.AddressPrimaryZip ,
			a.AddressPrimaryPlus4,
            a.AddressPrimaryCounty ,
            a.AddressPrimaryCountry ,
			a.AddressPrimaryIsCleanStatus,
            a.ContactGUID ,
            a.AddressOneStreet ,
			a.AddressOneSuite,
            a.AddressOneCity ,
            a.AddressOneState ,
            a.AddressOneZip ,
			a.AddressOnePlus4,
            a.AddressOneCounty ,
            a.AddressOneCountry ,
			a.AddressOneIsCleanStatus,
            a.AddressTwoStreet ,
			a.AddressTwoSuite,
            a.AddressTwoCity ,
            a.AddressTwoState ,
            a.AddressTwoZip ,
			a.AddressTwoPlus4,
            a.AddressTwoCounty ,
            a.AddressTwoCountry ,
			a.AddressTwoIsCleanStatus,
            a.AddressThreeStreet ,
			a.AddressThreeSuite,
            a.AddressThreeCity ,
            a.AddressThreeState ,
            a.AddressThreeZip ,
			a.AddressThreePlus4,
            a.AddressThreeCounty ,
            a.AddressThreeCountry ,
			a.AddressThreeIsCleanStatus,
            a.AddressFourStreet ,
			a.AddressFourSuite,
            a.AddressFourCity ,
            a.AddressFourState ,
            a.AddressFourZip ,
			a.AddressFourPlus4,
            a.AddressFourCounty ,
            a.AddressFourCountry ,
			a.AddressFourIsCleanStatus,
            a.PhonePrimary ,
			a.PhonePrimaryIsCleanStatus,
            a.PhoneHome ,
			a.PhoneHomeIsCleanStatus,
            a.PhoneCell ,
			a.PhoneCellIsCleanStatus,
            a.PhoneBusiness ,
			a.PhoneBusinessIsCleanStatus,
            a.PhoneFax ,
			a.PhoneFaxIsCleanStatus,
            a.PhoneOther ,
			a.PhoneOtherIsCleanStatus,
            a.EmailPrimary ,
			a.EmailPrimaryIsCleanStatus,
            a.EmailOne ,
			a.EmailOneIsCleanStatus,
            a.EmailTwo ,
			a.EmailTwoIsCleanStatus,
			a.CD_Gender AS InferredGender,
            CAST(a.ExtAttribute1 AS INT) AS DoNotMail ,
            CAST(a.ExtAttribute2 AS INT) AS DoNotEmail ,
			CAST(a.PhonePrimaryDNC AS INT) AS DoNotCall,
            a.SSCreatedBy ,
            a.SSUpdatedBy ,
            a.SSCreatedDate ,
            a.SSUpdatedDate ,
            a.CreatedBy ,
            a.UpdatedBy ,
            a.CreatedDate ,
            a.UpdatedDate ,
			a.ExtAttribute3 DeceasedConfirmationCode,
			a.ExtAttribute4 IsInactive,
			a.ExtAttribute6 Linked,
			a.ExtAttribute7 PIN,
			a.ExtAttribute8 HouseholdID,
			a.ExtAttribute9 HouseholdLookupID,
			a.ExtAttribute10 IsPrimaryHouseholdMember,
			CAST(a.ExtAttribute11 AS INT) IsPrimaryNeulionMember,
			CAST(a.ExtAttribute12 AS INT) Primary_MemberID,
			CAST(a.ExtAttribute13 AS INT) Primary_PatronID,
			CAST(a.Extattribute31 AS NVARCHAR(100)) BlackbaudStatus,
			CAST(a.ExtAttribute32 AS NVARCHAR(100)) NeulionStatus,
			CAST(a.ExtAttribute33 AS NVARCHAR(100)) PaciolanStatus,
			CAST(a.ExtAttribute35 AS NVARCHAR(100)) NeulionSalutation,
			CAST(a.ExtAttribute34 AS NVARCHAR(100)) NeulionEmail,
            a.AccountId ,
            a.AddressPrimaryNCOAStatus ,
            a.AddressOneStreetNCOAStatus ,
            a.AddressTwoStreetNCOAStatus ,
            a.AddressThreeStreetNCOAStatus ,
            a.AddressFourStreetNCOAStatus ,
			a.AddressPrimaryLatitude ,
            a.AddressPrimaryLongitude ,
            a.AddressOneLatitude ,
            a.AddressOneLongitude ,
            a.AddressTwoLatitude ,
            a.AddressTwoLongitude ,
            a.AddressThreeLatitude ,
            a.AddressThreeLongitude ,
            a.AddressFourLatitude ,
            a.AddressFourLongitude,
            CAST(a.IsBusiness AS INT) AS IsBusiness ,
            a.FullName ,
            CAST(c.SSB_CRMSYSTEM_PRIMARY_FLAG AS BIT) SSB_CRMSYSTEM_PRIMARY_FLAG ,
            a.Customer_matchkey AS CustomerMatchkey,
			c.DimCustomerSSBID
    FROM    dbo.DimCustomer AS a WITH (NOLOCK) 
    LEFT JOIN dbo.dimcustomerssbid AS c WITH (NOLOCK)
			ON a.DimCustomerId = c.DimCustomerId
    WHERE   a.IsDeleted = 0
			AND ISNULL(a.ExtAttribute4,0) <> '1'
			;

GO
