SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--Composite Record
CREATE VIEW [sas].[vw_CompositeRecord]
AS
SELECT  cr.SSB_CRMSYSTEM_CONTACT_ID,
		cr.DimCustomerId ,
        cr.SourceDB ,
        cr.SourceSystem ,
        cr.SSID ,
        cr.CustomerType ,
		cr.CustomerStatus,
        cr.CompanyName ,
        cr.SalutationName ,
        cr.DonorMailName ,
        cr.DonorFormalName ,
        cr.Birthday ,
        cr.Gender ,
        cr.MergedRecordFlag ,
        cr.Prefix ,
        cr.FirstName ,
        cr.MiddleName ,
        cr.LastName ,
        cr.Suffix ,
        cr.AddressPrimaryStreet ,
        cr.AddressPrimaryCity ,
        cr.AddressPrimaryState ,
        cr.AddressPrimaryZip ,
        cr.AddressPrimaryCounty ,
        cr.AddressPrimaryCountry ,
		cr.AddressPrimaryIsCleanStatus,
        cr.AddressOneStreet ,
        cr.AddressOneCity ,
        cr.AddressOneState ,
        cr.AddressOneZip ,
        cr.AddressOneCounty ,
        cr.AddressOneCountry ,
        cr.AddressTwoStreet ,
        cr.AddressTwoCity ,
        cr.AddressTwoState ,
        cr.AddressTwoZip ,
        cr.AddressTwoCounty ,
        cr.AddressTwoCountry ,
        cr.AddressThreeStreet ,
        cr.AddressThreeCity ,
        cr.AddressThreeState ,
        cr.AddressThreeZip ,
        cr.AddressThreeCounty ,
        cr.AddressThreeCountry ,
        cr.AddressFourStreet ,
        cr.AddressFourCity ,
        cr.AddressFourState ,
        cr.AddressFourZip ,
        cr.AddressFourCounty ,
        cr.AddressFourCountry ,
        cr.PhonePrimary ,
		cr.PhonePrimaryIsCleanStatus,
        cr.PhoneHome ,
        cr.PhoneCell ,
        cr.PhoneBusiness ,
        cr.PhoneFax ,
        cr.PhoneOther ,
        cr.EmailPrimary ,
		cr.EmailPrimaryIsCleanStatus,
        cr.EmailOne ,
        cr.EmailTwo ,
		CAST(cr.PhonePrimaryDNC AS INT) AS DoNotCall,
        TRY_CAST(cr.ExtAttribute1 AS INT) AS DoNotMail ,
        TRY_CAST(cr.ExtAttribute2 AS INT) AS DoNotEmail ,
		cr.ExtAttribute3 DeceasedConfirmationCode,
		cr.ExtAttribute4 IsInactive,
        cr.SSCreatedBy ,
        cr.SSUpdatedBy ,
        cr.SSCreatedDate ,
        cr.SSUpdatedDate ,
        cr.CreatedBy ,
        cr.UpdatedBy ,
        cr.CreatedDate ,
        cr.UpdatedDate ,
        cr.AccountId ,
        CAST(cr.IsBusiness AS INT) AS IsBusiness ,
        cr.FullName ,
		cr.AddressPrimaryLatitude,
        cr.AddressPrimaryLongitude ,
        cr.AddressOneLatitude ,
        cr.AddressOneLongitude ,
        cr.AddressTwoLatitude ,
        cr.AddressTwoLongitude ,
        cr.AddressThreeLatitude ,
        cr.AddressThreeLongitude ,
        cr.AddressFourLatitude ,
        cr.AddressFourLongitude ,
        cr.CD_Gender,
		cr.ExtAttribute6 Linked,
		cr.ExtAttribute7 PIN,
		cr.Extattribute8 HouseholdID,
		cr.ExtAttribute9 HouseholdLookupID,
		cr.ExtAttribute10 IsPrimaryMember,
		cr.Extattribute11 AS IsPrimaryNeulionMember,
		cr.ExtAttribute12 AS Primary_MemberID,
		cr.ExtAttribute13 AS Primary_PatronID,
		cr.ExtAttribute31 BlackbaudStatus,
		cr.ExtAttribute32 NeulionStatus,
		cr.ExtAttribute33 PaciolanStatus,
		cr.ExtAttribute34 NeulionEmail,
		cr.ExtAttribute35 NeulionSalutation

FROM    mdm.compositerecord cr WITH (NOLOCK)
WHERE	cr.IsDeleted <> 1;      

GO
