SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [sas].[vw_BB_Designation]
AS
SELECT  ID AS DesignationID ,
        DESIGNATIONNUMBER ,
        [DESCRIPTION] ,
        FRSNUMBER ,
        CAST(ISACTIVE AS INT) AS IsActive ,
        SITEID ,
        ADMINISTRATORID ,
        [DATE STATE PROFESSORSHIP APPROVED FOR QUEUE] AS DateSPApprovedForQueue ,
        [STATE PROFESSORSHIP STATUS] AS SPStatus ,
        [DATE STATE PROFESSORSHIP PAID] AS DateSPPaid ,
        [STATE PROFESSORSHIP GOAL AMOUNT] AS SPGoalAmount ,
        [DATE STATE PROFESSORSHIP MOVES TO ESCROW] AS DateSPMovesToEscrow ,
        [STATE PROFESSORSHIP DONOR] AS SPDonor ,
        [STATE MATCH AMOUNT RECEIVED] StateMatchAmountReceived ,
        [STATE MATCH AMOUNT PENDING] AS StateMatchAmountPending ,
        DESIGNATIONLEVELTYPE ,
        PSBUSINESSUNIT ,
        PSFUND ,
        PSSOURCE ,
        PSACCOUNT ,
        PSDEPARTMENT ,
        PSPROGRAM ,
        PSCOSTCODE1 ,
        PSCOSTCODE2 ,
        PSCOSTCODE3 ,
        PSACCOUNTNUMBER ,
        HIDEFROMONLINEGIVINGSEARCH ,
        CAST(DATEADDED AS DATE) DateAdded ,
        CAST(DATECHANGED AS DATE) DateUpdated
FROM    ods.BB_DESIGNATIONS   (NOLOCK)
WHERE IsActive = 1

GO
