SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--Blackbaud Pledge Balance
CREATE VIEW [sas].[vw_BB_PledgeBalance]
AS
SELECT  ID AS PledgeBalanceID ,
        FINANCIALTRANSACTIONID ,
        REVENUEID ,
        PLEDGEAMOUNT ,
        PLEDGEBALANCE ,
        PLEDGESPLITAMOUNT ,
        PLEDGESPLITBALANCE
FROM    ods.BB_PLEDGEBALANCE (NOLOCK)
GO
