SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [sascdmp].[CI_CAMPAIGN_GROUP_DATE_UDF] AS SELECT CAMPAIGN_GROUP_SK , DATE_UDF_NM , DATE_UDF_VAL , DATE_EXT_COLUMN_NM , PROCESSED_DTTM FROM sascdmp.CI_CAMP_GRP_PAGE_DATE_UDF WHERE PAGE_NM IN ('Brief Custom Details','BRIEF CUSTOM DETAILS')
GO
