CREATE TABLE [dbo].[SSB-SAAS_Data_Transfer_(CONTRIB)_201710150709]
(
[Member ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor Status Mod Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Points] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lifetime Giving Amount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lifetime Pledges] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lifetime Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Largest Gift Amount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Largest Gift Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Largest Gift Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Paid Date to Annual Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Paid to Annual Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last FY Paid to Annual Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[University Campaign 2022 Pledged] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[University Campaign 2022 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[All Gifts FY09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[17 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[17 Pledge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[17 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[17 Balance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[16 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[16 Pledge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[16 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[16 Balance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[15 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[15 Pledge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[15 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[15 Balance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[14 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[14 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[13 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[13 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[12 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[12 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[11 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[11 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[10 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[10 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[09 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[09 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[08 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[08 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[07 Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[07 Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA-2017?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA-2016?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA-2015?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA-2014?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Car Dealer?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Insurance Policy?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endowment Requirement] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Blue Zone Requirement] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endowment Heir?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[750K MB Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[750K MB Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[500K MB Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[500K MB Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[500K Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[500K Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[200K Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[200K Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[150K Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[150K Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[100K Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[100K Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[75K Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[75K Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[$35K-$50K Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[$35K-$50K Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[100K Half Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[100K Half Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[75K Half Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[75K Half Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[50K Half Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[50K Half Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[40K Half Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[40K Half Endowment Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[30K SR Life] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[30K SR Life Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[20K SR Life] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[20K SR Life Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[15K BR Life] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[15K BR Life Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[10K BR Life] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[10K BR Life Pd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Smith Center Heir?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBFF Pledged] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBFF Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endow Donor?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endow Pledged] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endow Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Insur Heir?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPECPROJ Level] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPECPROJ Pledged] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPECPROJ Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPECPROJ Balance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Basketball Practice Facility] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boshamer Stadium Maintenance Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boshamer Stadium Renovation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boshamer MLB,Visitors Lkr Rm and Team Room] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boshamer Stadium Improvements] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boshamer Stadium-Videoboard] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Brick Campaign-Sports Med Facility] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cheerleading Pride Floor Naming Opportunity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football Practice Complex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football Coaches' Locker Room] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football Special Funds] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Finley Clubhouse Pro] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Field Hockey Stadium New Renovation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gymnastics Practice Facility] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Henry Stadium Turf Project] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[James Gray Fball Mngr Schol Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Koury Box Mezzanine Program] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kenan Stadium Expansion] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Randy Gilbert 70s UNC Men's Lacrosse Film Room-Kenan Expansion] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kevin Reichardt-UNC Lacrosse Head Coach's Office in Memory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lacrosse Lkr Room-Kenan Expansion] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Locker Room Project Boshamer Stadium] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nutrition Center - Kenan Expansion] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Softball Hitting Facility] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Smith Center Basketball Offices Renovation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Smith Center Locker Suite Renovation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Misc-Soccer Lkr Room Renov] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Soccer Lacrosse Stadium - Future Designation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports Medicine Facility Proj] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports Medicine - M Thorp Performance Rehab Area] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Track and Field Sound System] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Volleyball Locker Room Project] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ernie Williamson Athletics Center] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wrestling Gymnastics Locker Room Project] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Willie Scroggs Locker Room Project] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Academic Support Center Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Charlie Justice Football Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Baseball Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eugene F  Brigham Track and Field Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carolina Family Basketball Project] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carolina Leadership Academy Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's And Women's Cross Country Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carolina Football Lettermens Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mens Basketball Excellence Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's And Women's Fencing Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Field Hockey Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gymnastics Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JV Basketball Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[J Knox Hillman Memorial Scholarship] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Joe Maddux Football Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[The 22 Club-Football Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[William R  Kenan, Jr  Endowment for Women's Soccer in Honor of Braxton Schell] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's And Women's Track Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's Basketball Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's Golf Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Volleyball Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Noah K Duncan Memorial Scholarship] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's Soccer Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[The Pope Performance Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Women's Lacrosse Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dean Smith Scholarship Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's Tennis Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Women's Basketball Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Women's Golf Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Men's Lacrosse Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Women's Soccer Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endowment Insurance Policy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rowing Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endowment-Campaign Carolina] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Women's Tennis Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Softball Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Women's Sports Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frank Comfort Scholarship Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carolina Swimming And Diving Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wrestling Operating Endowment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[National Championship Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[The 42 Campaign Fund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
