CREATE TABLE [dbo].[SSB-SAAS_Data_Transfer_CUS_DATA_201710160515]
(
[Member ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Davie ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor Status Mod Date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Contact] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary Contact] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prospect Stage] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Years Received YA Credit] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Highest Giving Level Requirement] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employer (Touchpoints)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title (Touchpoints)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Matching Gift Ratio (Touchpoints)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Match Min (Touchpoints)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Match Max (Touchpoints)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Years the Donor Has Upgraded] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Years the Donor has Downgraded] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Years the Donor has given 110%] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SR Years] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Previous Types of Payment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Years as Student Ram] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF Sign Up] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMG Staff Member] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMG Signup] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Courtside Passes (Men's Basketball)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Peebles Passes (Men's Basketball)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Joined] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQ AF16] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQ AF15] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQ AF14] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQ AF13] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQ AF12] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQ AF11] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQ AF10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endowed Scholarships] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WE Prospect Rating] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WE Net Worth] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WE Gift Capacity Range] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Abilitec ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Abilitec ID Duplicate?] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Consecutive Years Giving] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Years Giving] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExecBoard] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BoardAdvisors] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PastPresident] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Board of Trustees] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Big Hitter] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Campaigns] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Communication Received] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active Date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Login Date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Primary Title] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Primary First] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Primary Middle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Primary Last] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Primary Suf] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Primary Salutation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Secondary Title] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Secondary First] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Secondary Middle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Secondary Last] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Secondary Suf] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Secondary Salutation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Secondary Maiden] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Contact Info Notes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Other Account Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Business Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF17 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF16 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF15 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF14 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF13 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF12 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF11 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF10 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF09 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF08 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF07 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AF06 Retention] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Referring Member] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number Referred Members] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Value Referred Members] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Referral Credit Issued] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New Member Call] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Promo Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Need to contact donor] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Assigned need to contact] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UNC Athletics Staff] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefer ecommunication] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Solicit] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Only eBill] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Mail] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not Call] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do Not SMS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Membership Packet Sent Date ] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RC Special Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
