CREATE TABLE [dbo].[PD_PATRON_ATTRIBUTE]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PATRON] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VMC] [bigint] NOT NULL,
[ATTRIBUTE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[NOTE] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTRIBUTE_SOURCE] [bigint] NULL,
[ZID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[PD_PATRON_ATTRIBUTE] ADD CONSTRAINT [PK_PD_PATRON_ATTRIBUTE] PRIMARY KEY CLUSTERED  ([ETLSID], [PATRON], [VMC])
GO
