CREATE TABLE [dbo].[SYS_ZIP]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SYS_ZIP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CSZ] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[SYS_ZIP] ADD CONSTRAINT [PK_SYS_ZIP] PRIMARY KEY CLUSTERED  ([ETLSID], [SYS_ZIP])
GO
