CREATE TABLE [dbo].[Load_DimCustomer_BB]
(
[ID] [uniqueidentifier] NOT NULL,
[PRIMARYCONSTITUENCY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARY_EMPLOYER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INDIVIDUALFORMALSALUTATION] [nvarchar] (700) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INDIVIDUALINFORMALADDRESSEE] [nvarchar] (700) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INDIVIDUALFORMALADDRESSEE] [nvarchar] (700) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENDER] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_ADDRESSLINE1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_ADDRESSLINE2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_ADDRESSLINE3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_ADDRESSLINE4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_STATECODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_ZIPCODE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_COUNTRY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primadd_DoNotMail] [bit] NULL,
[home_ADDRESSLINE1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_ADDRESSLINE2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_ADDRESSLINE3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_ADDRESSLINE4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_STATECODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_ZIPCODE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_COUNTRY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_DoNotMail] [bit] NULL,
[bus_ADDRESSLINE1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_ADDRESSLINE2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_ADDRESSLINE3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_ADDRESSLINE4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_STATECODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_ZIPCODE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_COUNTRY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bus_DoNotMail] [bit] NULL,
[homeprev_ADDRESSLINE1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_ADDRESSLINE2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_ADDRESSLINE3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_ADDRESSLINE4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_STATECODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_ZIPCODE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_COUNTRY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeprev_DoNotMail] [bit] NULL,
[busprev_ADDRESSLINE1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_ADDRESSLINE2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_ADDRESSLINE3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_ADDRESSLINE4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_STATECODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_ZIPCODE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_COUNTRY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busprev_DoNotMail] [bit] NULL,
[Primphone_Number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primphone_DoNotCall] [bit] NULL,
[HomePhone_Number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone_DoNotCall] [bit] NULL,
[CellPhone_Number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CellPhone_DoNotCall] [bit] NULL,
[BusPhone_Number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusPhone_DoNotCall] [bit] NULL,
[Faxphone_Number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Faxphone_DoNotCall] [bit] NULL,
[primemail_EMAILADDRESS] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primemail_DoNotEmail] [bit] NULL,
[personalemail_EMAILADDRESS] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[personalemail_DoNotEmail] [bit] NULL,
[busemail_EMAILADDRESS] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[busemail_DoNotEmail] [bit] NULL,
[DECEASEDCONFIRMATIONCODE] [tinyint] NULL,
[ISINACTIVE] [bit] NULL,
[HOUSEHOLDID] [uniqueidentifier] NULL,
[HOUSEHOLDLOOKUPID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISPRIMARYMEMBER] [bit] NULL,
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_IsDeleted] [bit] NOT NULL,
[ETL_DeletedDate] [datetime] NULL,
[UpdatedDate] [date] NULL,
[LOOKUPID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPhone] [bit] NULL
)
GO
