CREATE TABLE [dbo].[TK_ITEM]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ITEM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BASIS] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CLASS] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[KEYWORD] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SELL_DATE_FROM] [datetime] NULL,
[SELL_DATE_TO] [datetime] NULL,
[SELL_TIME_FROM] [datetime] NULL,
[SELL_TIME_TO] [datetime] NULL,
[PTABLE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PRINT_LINE] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INTERNET_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[TK_ITEM] ADD CONSTRAINT [PK_TK_ITEM] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [ITEM])
GO
CREATE NONCLUSTERED INDEX [IDX_CLASS] ON [dbo].[TK_ITEM] ([CLASS])
GO
CREATE NONCLUSTERED INDEX [IDX_ITEM] ON [dbo].[TK_ITEM] ([ITEM])
GO
CREATE NONCLUSTERED INDEX [IDX_NAME] ON [dbo].[TK_ITEM] ([NAME])
GO
CREATE NONCLUSTERED INDEX [IDX_PTABLE] ON [dbo].[TK_ITEM] ([PTABLE])
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [dbo].[TK_ITEM] ([SEASON])
GO
