CREATE TABLE [dbo].[Addresses]
(
[LOOKUPID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDRESSTYPE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISACTIVE] [int] NOT NULL,
[ISPRIMARY] [bit] NOT NULL,
[ADDRESSLINE1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSLINE2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSLINE3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSLINE4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATECODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPCODE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRYCODE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEADDED] [date] NULL,
[DATECHANGED] [date] NULL,
[DONOTMAIL] [bit] NOT NULL,
[ISCONFIDENTIAL] [bit] NOT NULL,
[SEASONALSTARTDATE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEASONALENDDATE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HISTORICALSTARTDATE] [date] NULL,
[HISTORICALENDDATE] [date] NULL,
[COUNTY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
