CREATE TABLE [dbo].[TK_ORDER_RENEW]
(
[ETLSID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQ] [bigint] NOT NULL,
[VMC] [bigint] NOT NULL,
[RENEW_ITEM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RENEW_PL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RENEW_PT] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RENEW_FAC] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RENEW_QTY] [bigint] NULL,
[RENEW_SBLS] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[TK_ORDER_RENEW] ADD CONSTRAINT [PK_TK_ORDER_RENEW] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [CUSTOMER], [SEQ], [VMC])
GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER] ON [dbo].[TK_ORDER_RENEW] ([CUSTOMER])
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [dbo].[TK_ORDER_RENEW] ([SEASON])
GO
