CREATE TABLE [dbo].[TK_EGROUP]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SEASON] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[EGROUP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[TK_EGROUP] ADD CONSTRAINT [PK_TK_EGROUP] PRIMARY KEY CLUSTERED  ([ETLSID], [SEASON], [EGROUP])
GO
CREATE NONCLUSTERED INDEX [IDX_EGROUP] ON [dbo].[TK_EGROUP] ([EGROUP])
GO
CREATE NONCLUSTERED INDEX [IDX_SEASON] ON [dbo].[TK_EGROUP] ([SEASON])
GO
