CREATE TABLE [dbo].[EPD_ACCOUNT_DISTRIBUTOR]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CUSTOMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VMC] [bigint] NOT NULL,
[DISTRIBUTOR] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EMAIL] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINKED] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL_OK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[EPD_ACCOUNT_DISTRIBUTOR] ADD CONSTRAINT [PK_EPD_ACCOUNT_DISTRIBUTOR] PRIMARY KEY CLUSTERED  ([ETLSID], [CUSTOMER], [VMC])
GO
CREATE NONCLUSTERED INDEX [IDX_CUSTOMER] ON [dbo].[EPD_ACCOUNT_DISTRIBUTOR] ([CUSTOMER])
GO
CREATE NONCLUSTERED INDEX [IDX_Linked] ON [dbo].[EPD_ACCOUNT_DISTRIBUTOR] ([CUSTOMER], [LINKED])
GO
CREATE NONCLUSTERED INDEX [IDX_DISTRIBUTOR] ON [dbo].[EPD_ACCOUNT_DISTRIBUTOR] ([DISTRIBUTOR])
GO
