CREATE TABLE [ods].[SaaSContact]
(
[SaaSContact_SK] [int] NOT NULL IDENTITY(1, 1),
[BusinessKey_Hash] [binary] (64) NOT NULL,
[Attribute_Hash] [binary] (64) NULL,
[Member ID] [int] NULL,
[Account Status] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chapter Name] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[District Abbr] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Davie ID] [nvarchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [nvarchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor Status] [nvarchar] (46) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Birth] [nvarchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Joined] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Init] [nvarchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (53) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name Suffix] [nvarchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse Name] [nvarchar] (53) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse Title] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Address] [nvarchar] (67) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [nvarchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Phone] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bus. Ext] [nvarchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cell Phone] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill Address 1] [int] NULL,
[Bill Address 2] [int] NULL,
[Bill City] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill State Prov] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill Zip Code] [nvarchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill Country] [nvarchar] (43) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name/Phone/Email Mod Date] [datetime] NULL,
[Most Recent Contact Change Date] [datetime] NULL,
[Donor Status Mod Date] [datetime] NULL,
[Bill Address1] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill Address2] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROW_NUM] [int] NOT NULL,
[EFF_BEG_DATE] [date] NULL,
[EFF_END_DATE] [date] NOT NULL,
[ETL_CREATED_DATE] [datetime] NOT NULL,
[ETL_LUPDATED_DATE] [datetime] NOT NULL
)
GO
ALTER TABLE [ods].[SaaSContact] ADD CONSTRAINT [PK__SaaSCont__5106590E40A3D14B] PRIMARY KEY CLUSTERED  ([BusinessKey_Hash], [ROW_NUM], [EFF_END_DATE])
GO
