CREATE TABLE [ods].[BB_Designations_stg]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[ID] [uniqueidentifier] NOT NULL,
[DESIGNATIONNUMBER] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FRSNUMBER] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPARTMENT] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISACTIVE] [bit] NULL,
[SITEID] [uniqueidentifier] NULL,
[ADMINISTRATORID] [uniqueidentifier] NULL,
[DATE STATE PROFESSORSHIP APPROVED FOR QUEUE] [date] NULL,
[STATE PROFESSORSHIP STATUS] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE STATE PROFESSORSHIP PAID] [date] NULL,
[STATE PROFESSORSHIP GOAL AMOUNT] [money] NULL,
[DATE STATE PROFESSORSHIP MOVES TO ESCROW] [date] NULL,
[STATE PROFESSORSHIP DONOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE MATCH AMOUNT RECEIVED] [money] NULL,
[STATE MATCH AMOUNT PENDING] [money] NULL,
[DESIGNATIONLEVELTYPE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSBUSINESSUNIT] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSFUND] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSSOURCE] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSACCOUNT] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSDEPARTMENT] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSPROGRAM] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSCOSTCODE1] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSCOSTCODE2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSCOSTCODE3] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSACCOUNTNUMBER] [nvarchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HIDEFROMONLINEGIVINGSEARCH] [bit] NULL,
[DATEADDED] [date] NULL,
[DATECHANGED] [date] NULL
)
GO
ALTER TABLE [ods].[BB_Designations_stg] ADD CONSTRAINT [PK__BB_Desig__3214EC27285F898B] PRIMARY KEY CLUSTERED  ([ID])
GO
