CREATE TABLE [ods].[BB_Address_stg]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[ID] [uniqueidentifier] NOT NULL,
[CONSTITUENTID] [uniqueidentifier] NOT NULL,
[ADDRESSTYPE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISACTIVE] [bit] NOT NULL,
[ISPRIMARY] [bit] NOT NULL,
[ADDRESSLINE1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDRESSLINE2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDRESSLINE3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDRESSLINE4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CITY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATEID] [uniqueidentifier] NULL,
[STATE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATECODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPCODE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRYID] [uniqueidentifier] NOT NULL,
[COUNTRY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COUNTRYCODE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DONOTMAIL] [bit] NOT NULL,
[ISCONFIDENTIAL] [bit] NOT NULL,
[SEASONALSTARTDATE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEASONALENDDATE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HISTORICALSTARTDATE] [date] NULL,
[HISTORICALENDDATE] [date] NULL,
[COUNTY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATCHCODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATCHEDMETHOD] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LONGITUDE] [decimal] (16, 13) NULL,
[LATITUDE] [decimal] (16, 13) NULL,
[INFOSOURCE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEADDED] [date] NOT NULL,
[DATECHANGED] [date] NOT NULL
)
GO
ALTER TABLE [ods].[BB_Address_stg] ADD CONSTRAINT [PK_Address_ID] PRIMARY KEY CLUSTERED  ([ID])
GO
