CREATE TABLE [sas].[rpt_RamsClubDonations_test]
(
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberID] [int] NULL,
[DonorStatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerStatus] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rank] [int] NULL,
[Points] [money] NULL,
[LifetimeGivingAmount] [money] NULL,
[LifetimePledges] [money] NULL,
[LifetimePaid] [money] NULL,
[LargestGiftAmount] [money] NULL,
[LargestGiftDate] [datetime] NULL,
[LargestGiftFund] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstPaidDateToAnnualFund] [datetime] NULL,
[LastPaidDateToAnnualFund] [datetime] NULL,
[LastFYPaidToAnnualFund] [int] NULL,
[UniversityCampaign2022Pledged] [money] NULL,
[UniversityCampaign2022Paid] [money] NULL,
[AllGiftsFY18] [money] NULL,
[AllGiftsFY17] [money] NULL,
[AllGiftsFY16] [money] NULL,
[AllGiftsFY15] [money] NULL,
[AllGiftsFY14] [money] NULL,
[AllGiftsFY13] [money] NULL,
[AllGiftsFY12] [money] NULL,
[AllGiftsFY11] [money] NULL,
[AllGiftsFY10] [money] NULL,
[AllGiftsFY09] [money] NULL,
[Status18] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pledge18] [money] NULL,
[Paid18] [money] NULL,
[Balance18] [money] NULL,
[Status17] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pledge17] [money] NULL,
[Paid17] [money] NULL,
[Balance17] [money] NULL,
[Status16] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pledge16] [money] NULL,
[Paid16] [money] NULL,
[Balance16] [money] NULL,
[Status15] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pledge15] [money] NULL,
[Paid15] [money] NULL,
[Balance15] [money] NULL,
[Status14] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid14] [money] NULL,
[Status13] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid13] [money] NULL,
[Status12] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid12] [money] NULL,
[Status11] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid11] [money] NULL,
[Status10] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid10] [money] NULL,
[Status09] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid09] [money] NULL,
[Status08] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid08] [money] NULL,
[Status07] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paid07] [money] NULL,
[YA2018] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA2017] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA2016] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA2015] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YA2014] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF16] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF15] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF14] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF13] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF12] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF11] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF10] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalYearsGiving] [int] NULL,
[YearsAsStudentRam] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConsecutiveYearsGiving] [int] NULL,
[YearsReceivedYACredit] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearsDonorHasUpgraded] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearsDonorHasDowngraded] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearsDonorHasGiven110Percent] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarDealer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsurancePolicy] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentRequirement] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BlueZoneRequirement] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentHeir] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endowment750KMB] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd750KMB] [money] NULL,
[Endowment500KMB] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd500KMB] [money] NULL,
[Endowment500K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd500K] [money] NULL,
[Endowment200K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd200K] [money] NULL,
[Endowment150K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd150K] [money] NULL,
[Endowment100K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd100K] [money] NULL,
[Endowment75K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd75K] [money] NULL,
[Endowment35K_50K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowmentPd35K_50K] [money] NULL,
[HalfEndowment100K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HalfEndowmentPd100K] [money] NULL,
[HalfEndowment75K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HalfEndowmentPd75K] [money] NULL,
[HalfEndowment50K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HalfEndowmentPd50K] [money] NULL,
[HalfEndowment40K] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HalfEndowmentPd40K] [money] NULL,
[Life30KSR] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifePd30KSR] [money] NULL,
[Life20KSR] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifePd20KSR] [money] NULL,
[Life15KSR] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifePd15KBR] [money] NULL,
[Life10KSR] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifePd10KBR] [money] NULL,
[SmithCenterHeir] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBFFPledged] [money] NULL,
[CBFFPaid] [money] NULL,
[EndowDonor] [nvarchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowPledged] [money] NULL,
[EndowPaid] [money] NULL,
[InsurHeir] [nvarchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPECPROJLevel] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPECPROJPledged] [money] NULL,
[SPECPROJPaid] [money] NULL,
[SPECPROJBalance] [money] NULL,
[BasketballPracticeFacility] [money] NULL,
[BosStaMaintenanceEndow] [money] NULL,
[BoshamerStadiumRenovation] [money] NULL,
[BosMLBVisitorsLkrRmAndTeamRoom] [money] NULL,
[BoshamerStadiumImprovements] [money] NULL,
[BoshamerStadium_Videoboard] [money] NULL,
[BrickCamp_SportsMedFacility] [money] NULL,
[CheerleadingPrideFloorNamingOp] [money] NULL,
[FootballPracticeComplex] [money] NULL,
[FootballCoachesLockerRoom] [money] NULL,
[FootballSpecialFunds] [money] NULL,
[FinleyClubhousePro] [money] NULL,
[FieldHockeyStadiumNewRenov] [money] NULL,
[GymnasticsPracticeFacility] [money] NULL,
[HenryStadiumTurfProject] [money] NULL,
[JGFballMngrScholEndo] [money] NULL,
[KouryBoxMezzanineProgram] [money] NULL,
[KenanStadiumExpansion] [money] NULL,
[RG70sUNCMensLXFilmRoomKenanExp] [money] NULL,
[KR_UNCLXHeadCoachsOfficeinMem] [money] NULL,
[LacrosseLkrRoom_KenanExpansion] [money] NULL,
[LockerRoomProjectBosSta] [money] NULL,
[NutritionCenter_KenanExpansion] [money] NULL,
[SoftballHittingFacility] [money] NULL,
[SCBasketballOfficesRenov] [money] NULL,
[SCLockerSuiteRenov] [money] NULL,
[Misc_SoccerLkrRoomRenov] [money] NULL,
[SoccerLXStadium_FutureDesig] [money] NULL,
[SportsMedicineFacilityProj] [money] NULL,
[SportsMedicine_MTPerfRehabArea] [money] NULL,
[TrackAndFieldSoundSystem] [money] NULL,
[VolleyballLockerRoomProject] [money] NULL,
[ErnieWilliamsonAthleticsCenter] [money] NULL,
[WresGymLockerRoomProject] [money] NULL,
[WillieScroggsLockerRoomProject] [money] NULL,
[AcademicSCOperatingEndo] [money] NULL,
[CharlieJusticeFootballOpEndo] [money] NULL,
[FootballOperatingEndowment] [money] NULL,
[BaseballOperatingEndowment] [money] NULL,
[EugeneFBrighamTnFieldOpEndo] [money] NULL,
[CaroFamilyBBProject] [money] NULL,
[CaroLeadershipAcademyEndo] [money] NULL,
[MnWCrossCountryOperatingEndo] [money] NULL,
[CaroFBLettermensOperatingEndo] [money] NULL,
[MensBasketballExcellenceFund] [money] NULL,
[MnWFencingOperatingEndo] [money] NULL,
[FieldHockeyOperatingEndowment] [money] NULL,
[GymnasticsOperatingEndowment] [money] NULL,
[JVBasketballOperatingEndowment] [money] NULL,
[JKnoxHillmanMemorialSchol] [money] NULL,
[JoeMadduxFBOperatingEndo] [money] NULL,
[The22Club_FBOperatingEndo] [money] NULL,
[WKEndoforWomensSoccerHonorofBS] [money] NULL,
[MnWTrackOperatingEndo] [money] NULL,
[MensBBOperatingEndo] [money] NULL,
[MensGolfOperatingEndowment] [money] NULL,
[VolleyballOperatingEndowment] [money] NULL,
[NoahKDuncanMemorialScholarship] [money] NULL,
[MensSoccerOperatingEndowment] [money] NULL,
[ThePopePerformanceFund] [money] NULL,
[WomensLXOperatingEndo] [money] NULL,
[DeanSmithScholarshipEndowment] [money] NULL,
[MensTennisOperatingEndowment] [money] NULL,
[WomensBBOperatingEndo] [money] NULL,
[WomensGolfOperatingEndowment] [money] NULL,
[MensLacrosseOperatingEndowment] [money] NULL,
[WomensSoccerOperatingEndowment] [money] NULL,
[EndowmentInsurancePolicy] [money] NULL,
[RowingOperatingEndowment] [money] NULL,
[Endowment_CampaignCarolina] [money] NULL,
[WomensTennisOperatingEndowment] [money] NULL,
[SoftballOperatingEndowment] [money] NULL,
[WomensSportsEndowment] [money] NULL,
[FrankComfortScholEndo] [money] NULL,
[CaroSnDOperatingEndo] [money] NULL,
[WrestlingOperatingEndowment] [money] NULL
)
GO
