CREATE TABLE [sascdm].[CI_COMMUNICATION_EXT]
(
[COMMUNICATION_SK] [numeric] (15, 0) NOT NULL
)
GO
ALTER TABLE [sascdm].[CI_COMMUNICATION_EXT] ADD CONSTRAINT [COMM_EXT_PK] PRIMARY KEY CLUSTERED  ([COMMUNICATION_SK])
GO
ALTER TABLE [sascdm].[CI_COMMUNICATION_EXT] ADD CONSTRAINT [COMM_EXT_FK1] FOREIGN KEY ([COMMUNICATION_SK]) REFERENCES [sascdm].[CI_COMMUNICATION] ([COMMUNICATION_SK])
GO
