CREATE TABLE [sascdmp].[CI_CONTACT_HISTORY]
(
[CELL_PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_DTTM] [datetime] NOT NULL,
[CONTACT_DT] [date] NULL,
[CONTACT_HISTORY_STATUS_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PACKAGE_HASH_VAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPTIMIZATION_BACKFILL_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTERNAL_CONTACT_INFO_ID1] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTERNAL_CONTACT_INFO_ID2] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESPONSE_TRACKING_CD] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdmp].[CI_CONTACT_HISTORY] ADD CONSTRAINT [CONT_HIST_PK] PRIMARY KEY CLUSTERED  ([CELL_PACKAGE_SK], [SSB_CRMSYSTEM_CONTACT_ID], [CONTACT_DTTM])
GO
CREATE NONCLUSTERED INDEX [CONT_HIST_IX01] ON [sascdmp].[CI_CONTACT_HISTORY] ([SSB_CRMSYSTEM_CONTACT_ID], [CONTACT_DTTM], [CELL_PACKAGE_SK], [PACKAGE_HASH_VAL])
GO
