CREATE TABLE [sascdm].[CI_EXTERNAL_CONTACT]
(
[EXTERNAL_CONTACT_SK] [numeric] (15, 0) NOT NULL,
[SUBJECT_ID] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_DT] [date] NOT NULL,
[CONTACT_DTTM] [datetime] NOT NULL,
[EXTERNAL_CONT_RESP_DET_SK] [numeric] (15, 0) NOT NULL
)
GO
ALTER TABLE [sascdm].[CI_EXTERNAL_CONTACT] ADD CONSTRAINT [EXTERNAL_CONTACT_PK] PRIMARY KEY CLUSTERED  ([EXTERNAL_CONTACT_SK])
GO
ALTER TABLE [sascdm].[CI_EXTERNAL_CONTACT] ADD CONSTRAINT [EXTERNAL_CONTACT_FK1] FOREIGN KEY ([EXTERNAL_CONT_RESP_DET_SK]) REFERENCES [sascdm].[CI_EXTERNAL_CONT_RESP_DETAIL] ([EXTERNAL_CONT_RESP_DET_SK])
GO
