CREATE TABLE [sascdmp].[CI_TREATMENT]
(
[TREATMENT_SK] [numeric] (15, 0) NOT NULL,
[TREATMENT_CD] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREATMENT_VERSION_NO] [numeric] (6, 0) NULL,
[TREATMENT_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREATMENT_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREATMENT_REFERENCE_TXT] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREATMENT_REFERENCE_URL] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRENT_VERSION_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[START_DTTM] [datetime] NULL,
[END_DTTM] [datetime] NULL,
[DELETED_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESSED_DTTM] [datetime] NULL
)
GO
ALTER TABLE [sascdmp].[CI_TREATMENT] ADD CONSTRAINT [TREATMENT_PK] PRIMARY KEY CLUSTERED  ([TREATMENT_SK])
GO
