CREATE TABLE [sascdm].[CI_RESPONSE]
(
[RESPONSE_SK] [numeric] (15, 0) NOT NULL,
[RESPONSE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RESPONSE_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_RESPONSE] ADD CONSTRAINT [RESPONSE_PK] PRIMARY KEY CLUSTERED  ([RESPONSE_SK])
GO
