CREATE TABLE [sascdmp].[CI_CAMPAIGN_EXT]
(
[CAMPAIGN_SK] [numeric] (15, 0) NOT NULL,
[CAMPAIGN_TYPE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_BUS_OWNER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_DEVELOPER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_STRATEGY] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_START_DT] [datetime] NULL,
[CAMPAIGN_END_DT] [datetime] NULL
)
GO
ALTER TABLE [sascdmp].[CI_CAMPAIGN_EXT] ADD CONSTRAINT [CAMP_EXT_PK1] PRIMARY KEY CLUSTERED  ([CAMPAIGN_SK])
GO
ALTER TABLE [sascdmp].[CI_CAMPAIGN_EXT] ADD CONSTRAINT [CAMP_EXT_FK2] FOREIGN KEY ([CAMPAIGN_SK]) REFERENCES [sascdmp].[CI_CAMPAIGN] ([CAMPAIGN_SK])
GO
