CREATE TABLE [sascdm].[CI_CONTACT_RULE_TYPE]
(
[CONTACT_RULE_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_RULE_TYPE_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_CONTACT_RULE_TYPE] ADD CONSTRAINT [CONT_RULE_TYPE_PK] PRIMARY KEY CLUSTERED  ([CONTACT_RULE_TYPE_CD])
GO
