CREATE TABLE [sascdmp].[CI_CONTROL_GROUP_TYPE]
(
[CONTROL_GROUP_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTROL_GROUP_TYPE_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdmp].[CI_CONTROL_GROUP_TYPE] ADD CONSTRAINT [CTRL_GRP_TYPE_PK] PRIMARY KEY CLUSTERED  ([CONTROL_GROUP_TYPE_CD])
GO
