CREATE TABLE [sascdmp].[CI_CONTACT_RULE_INTERVAL]
(
[CONTACT_RULE_INTERVAL_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_RULE_INTERVAL_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdmp].[CI_CONTACT_RULE_INTERVAL] ADD CONSTRAINT [CONT_RULE_INTERVAL_PK] PRIMARY KEY CLUSTERED  ([CONTACT_RULE_INTERVAL_CD])
GO
