CREATE TABLE [sascdm].[Model_46459f9de5a54cbfac128dd2]
(
[sid0] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[scoreSegment] [bigint] NULL,
[score] [bigint] NULL,
[scoreClass] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorMailName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[flgGenPub] [bigint] NULL,
[flgInternet] [bigint] NULL,
[flgAlum] [bigint] NULL,
[flgRcntGrad] [bigint] NULL,
[flgParent] [bigint] NULL,
[d2ch] [bigint] NULL,
[seasonsFB] [bigint] NULL,
[totTF] [bigint] NULL,
[totSeatsFB] [bigint] NULL,
[totGamesFB] [bigint] NULL,
[avgSeatsFB] [bigint] NULL,
[avgGamesFB] [bigint] NULL,
[avgPLCFB] [bigint] NULL,
[rankFB] [bigint] NULL,
[seasonLastFB] [bigint] NULL,
[boughtLastFB] [bigint] NULL,
[seasonPastFB] [bigint] NULL,
[boughtPastFB] [bigint] NULL,
[seasonsMB] [bigint] NULL,
[totSeatsMB] [bigint] NULL,
[totGamesMB] [bigint] NULL,
[avgSeatsMB] [bigint] NULL,
[avgGamesMB] [bigint] NULL,
[avgPLCMB] [bigint] NULL,
[rankMB] [bigint] NULL,
[seasonLastMB] [bigint] NULL,
[boughtLastMB] [bigint] NULL,
[seasonPastMB] [bigint] NULL,
[boughtPastMB] [bigint] NULL,
[nDonations] [bigint] NULL,
[avgDonation] [bigint] NULL,
[minDonation] [bigint] NULL,
[maxDonation] [bigint] NULL,
[rngDonation] [bigint] NULL,
[firstD] [bigint] NULL,
[lastD] [bigint] NULL,
[TimeSinceLastDonation] [bigint] NULL,
[TimeSinceFirstDonation] [bigint] NULL,
[rtoActiv] [bigint] NULL,
[TotDeptAthDons] [bigint] NULL,
[TotFootballDons] [bigint] NULL,
[TotBasketballDons] [bigint] NULL,
[TotDeptAthAmt] [bigint] NULL,
[TotDonationAmt] [bigint] NULL,
[rankDonationAmt] [bigint] NULL,
[rankNumDonations] [bigint] NULL,
[EventsAttended] [bigint] NULL,
[EventsSince2016] [bigint] NULL,
[SportsEventsSince2016] [bigint] NULL,
[TotSports] [bigint] NULL,
[TotAlumni] [bigint] NULL,
[TotReunions] [bigint] NULL,
[TotHC] [bigint] NULL,
[TotFastBreak] [bigint] NULL,
[TotGolf] [bigint] NULL,
[TotCWC] [bigint] NULL,
[TotOther] [bigint] NULL,
[rankEventsAttended] [bigint] NULL,
[LifetimeGivingAmount] [bigint] NULL,
[rankRam] [bigint] NULL,
[points] [bigint] NULL,
[TarHeel] [bigint] NULL,
[targetRam] [bigint] NULL,
[targetFB] [bigint] NULL,
[targetMB] [bigint] NULL,
[rankScore] [bigint] NULL
)
GO
