CREATE TABLE [sascdmp].[CI_COMMUNICATION_RECURR_TYPE]
(
[COMMUNICATION_RECURR_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMUNICATION_RECURR_TYPE_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdmp].[CI_COMMUNICATION_RECURR_TYPE] ADD CONSTRAINT [COMM_RECURR_TYPE_PK] PRIMARY KEY CLUSTERED  ([COMMUNICATION_RECURR_TYPE_CD])
GO
