CREATE TABLE [sascdm].[CI_CELL_PACKAGE]
(
[CELL_PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[CAMPAIGN_SK] [numeric] (15, 0) NOT NULL,
[CAMPAIGN_CD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMUNICATION_SK] [numeric] (15, 0) NOT NULL,
[COMMUNICATION_CD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMUNICATION_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMUNICATION_OCCURRENCE_NO] [numeric] (6, 0) NULL,
[MARKETING_CELL_SK] [numeric] (15, 0) NOT NULL,
[MARKETING_CELL_CD] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MARKETING_CELL_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MARKETING_CELL_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PACKAGE_SK] [numeric] (15, 0) NULL,
[PACKAGE_CD] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHANNEL_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBJECT_TYPE_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTROL_GROUP_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTAL_PREOPTIMIZED_CONTACT_CNT] [numeric] (10, 0) NULL,
[TRACK_PRESENTED_TREATMENTS_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAX_TREATMENT_CNT] [numeric] (6, 0) NULL,
[DELETED_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESPONSE_TRACKING_CD] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESSED_DTTM] [datetime] NULL
)
GO
ALTER TABLE [sascdm].[CI_CELL_PACKAGE] ADD CONSTRAINT [CELL_PKG_PK] PRIMARY KEY CLUSTERED  ([CELL_PACKAGE_SK])
GO
ALTER TABLE [sascdm].[CI_CELL_PACKAGE] WITH NOCHECK ADD CONSTRAINT [CELL_PKG_FK1] FOREIGN KEY ([COMMUNICATION_SK]) REFERENCES [sascdm].[CI_COMMUNICATION] ([COMMUNICATION_SK])
GO
ALTER TABLE [sascdm].[CI_CELL_PACKAGE] WITH NOCHECK ADD CONSTRAINT [CELL_PKG_FK2] FOREIGN KEY ([CAMPAIGN_SK]) REFERENCES [sascdm].[CI_CAMPAIGN] ([CAMPAIGN_SK])
GO
ALTER TABLE [sascdm].[CI_CELL_PACKAGE] WITH NOCHECK ADD CONSTRAINT [CELL_PKG_FK3] FOREIGN KEY ([MARKETING_CELL_SK]) REFERENCES [sascdm].[CI_MARKETING_CELL] ([MARKETING_CELL_SK])
GO
ALTER TABLE [sascdm].[CI_CELL_PACKAGE] WITH NOCHECK ADD CONSTRAINT [CELL_PKG_FK4] FOREIGN KEY ([CONTROL_GROUP_TYPE_CD]) REFERENCES [sascdm].[CI_CONTROL_GROUP_TYPE] ([CONTROL_GROUP_TYPE_CD])
GO
ALTER TABLE [sascdm].[CI_CELL_PACKAGE] WITH NOCHECK ADD CONSTRAINT [CELL_PKG_FK5] FOREIGN KEY ([PACKAGE_SK]) REFERENCES [sascdm].[CI_PACKAGE] ([PACKAGE_SK])
GO
