CREATE TABLE [sascdm].[CI_CAMPAIGN_STATUS]
(
[CAMPAIGN_STATUS_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CAMPAIGN_STATUS_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_CAMPAIGN_STATUS] ADD CONSTRAINT [CAMP_STATUS_PK] PRIMARY KEY CLUSTERED  ([CAMPAIGN_STATUS_CD])
GO
