CREATE TABLE [sascdm].[CI_CAMPAIGN_GROUP_TYPE]
(
[CAMPAIGN_GROUP_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CAMPAIGN_GROUP_TYPE_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_CAMPAIGN_GROUP_TYPE] ADD CONSTRAINT [CAMP_GRP_TYPE_PK] PRIMARY KEY CLUSTERED  ([CAMPAIGN_GROUP_TYPE_CD])
GO
