CREATE TABLE [sascdm].[CI_COMMUNICATION_STATUS]
(
[COMMUNICATION_STATUS_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMUNICATION_STATUS_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_COMMUNICATION_STATUS] ADD CONSTRAINT [COMM_STATUS_PK] PRIMARY KEY CLUSTERED  ([COMMUNICATION_STATUS_CD])
GO
