CREATE TABLE [sascdm].[CI_STAGING_DATA]
(
[BUSINESS_CONTEXT_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUBJECT_ID_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUBJECT_HASH_VAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CHANNEL_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_SK] [numeric] (15, 0) NOT NULL,
[TREATMENT_ID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_COLUMN_ID] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREATMENT_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_CD] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_DESC] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREATMENT_FOLDER_TXT] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_REFERENCE_URL] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREATMENT_REFERENCE_TXT] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTRIBUTING_CELL_PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[TREATMENT_HASH_VAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_SCORE] [numeric] (3, 2) NULL,
[TREATMENT_RANDOM_SCORE_FLG] [numeric] (1, 0) NOT NULL,
[STAGED_DTTM] [datetime] NOT NULL,
[STAGED_CNT] [numeric] (3, 0) NOT NULL,
[START_DTTM] [datetime] NULL,
[END_DTTM] [datetime] NULL,
[TARGET_START_DTTM] [datetime] NULL,
[TARGET_END_DTTM] [datetime] NULL,
[TREATMENT_CNT] [numeric] (3, 0) NOT NULL,
[CUSTOM_FIELDS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOM_LIST_FIELDS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESSED_DTTM] [datetime] NOT NULL
)
GO
ALTER TABLE [sascdm].[CI_STAGING_DATA] ADD CONSTRAINT [STAGING_PK] PRIMARY KEY CLUSTERED  ([BUSINESS_CONTEXT_CD], [SUBJECT_ID_CD], [SUBJECT_HASH_VAL], [CHANNEL_CD], [TREATMENT_HASH_VAL], [PROCESSED_DTTM])
GO
