CREATE TABLE [sascdmp].[CI_CAMPAIGN_GROUP_STATUS]
(
[CAMPAIGN_GROUP_STATUS_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CAMPAIGN_GROUP_STATUS_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdmp].[CI_CAMPAIGN_GROUP_STATUS] ADD CONSTRAINT [CAMP_GRP_STATUS_PK] PRIMARY KEY CLUSTERED  ([CAMPAIGN_GROUP_STATUS_CD])
GO
