CREATE TABLE [sascdmp].[CI_PACKAGE_X_TREATMENT]
(
[PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[PACKAGE_HASH_VAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_SK] [numeric] (15, 0) NOT NULL,
[CONTRIBUTING_CELL_PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[SEQUENCE_NO] [numeric] (6, 0) NOT NULL
)
GO
ALTER TABLE [sascdmp].[CI_PACKAGE_X_TREATMENT] ADD CONSTRAINT [PKG_X_TREAT_PK] PRIMARY KEY CLUSTERED  ([PACKAGE_SK], [PACKAGE_HASH_VAL], [TREATMENT_SK], [CONTRIBUTING_CELL_PACKAGE_SK], [SEQUENCE_NO])
GO
CREATE NONCLUSTERED INDEX [PKG_TREAT_IX01] ON [sascdmp].[CI_PACKAGE_X_TREATMENT] ([PACKAGE_HASH_VAL])
GO
ALTER TABLE [sascdmp].[CI_PACKAGE_X_TREATMENT] ADD CONSTRAINT [PKG_X_TREAT_FK1] FOREIGN KEY ([PACKAGE_SK]) REFERENCES [sascdmp].[CI_PACKAGE] ([PACKAGE_SK])
GO
ALTER TABLE [sascdmp].[CI_PACKAGE_X_TREATMENT] ADD CONSTRAINT [PKG_X_TREAT_FK2] FOREIGN KEY ([TREATMENT_SK]) REFERENCES [sascdmp].[CI_TREATMENT] ([TREATMENT_SK])
GO
ALTER TABLE [sascdmp].[CI_PACKAGE_X_TREATMENT] ADD CONSTRAINT [PKG_X_TREAT_FK3] FOREIGN KEY ([CONTRIBUTING_CELL_PACKAGE_SK]) REFERENCES [sascdmp].[CI_CELL_PACKAGE] ([CELL_PACKAGE_SK])
GO
