CREATE TABLE [sascdm].[CI_CAMPAIGN_EXT]
(
[CAMPAIGN_SK] [numeric] (15, 0) NOT NULL,
[CAMPAIGN_TYPE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_BUS_OWNER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_DEVELOPER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_STRATEGY] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPAIGN_START_DT] [date] NULL,
[CAMPAIGN_END_DT] [date] NULL
)
GO
ALTER TABLE [sascdm].[CI_CAMPAIGN_EXT] ADD CONSTRAINT [CAMP_EXT_PK] PRIMARY KEY CLUSTERED  ([CAMPAIGN_SK])
GO
ALTER TABLE [sascdm].[CI_CAMPAIGN_EXT] WITH NOCHECK ADD CONSTRAINT [CAMP_EXT_FK1] FOREIGN KEY ([CAMPAIGN_SK]) REFERENCES [sascdm].[CI_CAMPAIGN] ([CAMPAIGN_SK])
GO
