CREATE TABLE [sascdm].[CI_CHANGE_TYPE]
(
[CHANGE_TYPE_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CHANGE_TYPE_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_CHANGE_TYPE] ADD CONSTRAINT [CHANGE_TYPE_PK] PRIMARY KEY CLUSTERED  ([CHANGE_TYPE_CD])
GO
