CREATE TABLE [sascdm].[CI_TREATMENT_UDF_TAG]
(
[TREATMENT_SK] [numeric] (15, 0) NOT NULL,
[UDF_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UDF_TAG_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_TREATMENT_UDF_TAG] ADD CONSTRAINT [TREAT_UDF_TAG_PK] PRIMARY KEY CLUSTERED  ([TREATMENT_SK], [UDF_NM])
GO
ALTER TABLE [sascdm].[CI_TREATMENT_UDF_TAG] ADD CONSTRAINT [TREAT_UDF_TAG_FK1] FOREIGN KEY ([TREATMENT_SK]) REFERENCES [sascdm].[CI_TREATMENT] ([TREATMENT_SK])
GO
