CREATE TABLE [sascdmp].[CI_RESPONSE_X_CELL_PACKAGE]
(
[RESPONSE_SK] [numeric] (15, 0) NOT NULL,
[CELL_PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[RESPONSE_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTIMATED_RESPONSE_RT] [numeric] (9, 4) NULL
)
GO
ALTER TABLE [sascdmp].[CI_RESPONSE_X_CELL_PACKAGE] ADD CONSTRAINT [RESP_X_CPKG_PK] PRIMARY KEY CLUSTERED  ([RESPONSE_SK], [CELL_PACKAGE_SK])
GO
ALTER TABLE [sascdmp].[CI_RESPONSE_X_CELL_PACKAGE] ADD CONSTRAINT [RESP_X_CPKG_FK1] FOREIGN KEY ([CELL_PACKAGE_SK]) REFERENCES [sascdmp].[CI_CELL_PACKAGE] ([CELL_PACKAGE_SK])
GO
ALTER TABLE [sascdmp].[CI_RESPONSE_X_CELL_PACKAGE] ADD CONSTRAINT [RESP_X_CPKG_FK2] FOREIGN KEY ([RESPONSE_SK]) REFERENCES [sascdmp].[CI_RESPONSE] ([RESPONSE_SK])
GO
ALTER TABLE [sascdmp].[CI_RESPONSE_X_CELL_PACKAGE] ADD CONSTRAINT [RESP_X_CPKG_FK3] FOREIGN KEY ([RESPONSE_TYPE_CD]) REFERENCES [sascdmp].[CI_RESPONSE_TYPE] ([RESPONSE_TYPE_CD])
GO
