CREATE TABLE [sascdm].[CI_RESPONSE_CHANNEL_RESPONSE]
(
[RESPONSE_CHANNEL_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RESPONSE_CHANNEL_RESPONSE_CD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RESPONSE_SK] [numeric] (15, 0) NOT NULL
)
GO
ALTER TABLE [sascdm].[CI_RESPONSE_CHANNEL_RESPONSE] ADD CONSTRAINT [RSP_CHL_RSP_PK] PRIMARY KEY CLUSTERED  ([RESPONSE_CHANNEL_CD], [RESPONSE_CHANNEL_RESPONSE_CD], [RESPONSE_SK])
GO
ALTER TABLE [sascdm].[CI_RESPONSE_CHANNEL_RESPONSE] ADD CONSTRAINT [RSP_CHL_RSP_FK1] FOREIGN KEY ([RESPONSE_CHANNEL_CD]) REFERENCES [sascdm].[CI_CHANNEL] ([CHANNEL_CD])
GO
ALTER TABLE [sascdm].[CI_RESPONSE_CHANNEL_RESPONSE] ADD CONSTRAINT [RSP_CHL_RSP_FK2] FOREIGN KEY ([RESPONSE_SK]) REFERENCES [sascdm].[CI_RESPONSE] ([RESPONSE_SK])
GO
