CREATE TABLE [sascdmp].[CI_MARKETING_CELL]
(
[MARKETING_CELL_SK] [numeric] (15, 0) NOT NULL,
[CAMPAIGN_SK] [numeric] (15, 0) NOT NULL,
[MARKETING_CELL_CD] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MARKETING_CELL_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MARKETING_CELL_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTROL_GROUP_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESSED_DTTM] [datetime] NULL
)
GO
ALTER TABLE [sascdmp].[CI_MARKETING_CELL] ADD CONSTRAINT [MKTG_CELL_PK] PRIMARY KEY CLUSTERED  ([MARKETING_CELL_SK])
GO
ALTER TABLE [sascdmp].[CI_MARKETING_CELL] ADD CONSTRAINT [MKTG_CELL_FK1] FOREIGN KEY ([CAMPAIGN_SK]) REFERENCES [sascdmp].[CI_CAMPAIGN] ([CAMPAIGN_SK])
GO
ALTER TABLE [sascdmp].[CI_MARKETING_CELL] ADD CONSTRAINT [MKTG_CELL_FK2] FOREIGN KEY ([CONTROL_GROUP_TYPE_CD]) REFERENCES [sascdmp].[CI_CONTROL_GROUP_TYPE] ([CONTROL_GROUP_TYPE_CD])
GO
