CREATE TABLE [sascdmp].[CI_EXTERNAL_RESPONSE]
(
[EXTERNAL_RESPONSE_SK] [numeric] (15, 0) NOT NULL,
[SUBJECT_ID] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RESPONSE_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RESPONSE_DT] [date] NOT NULL,
[RESPONSE_DTTM] [datetime] NOT NULL,
[EXTERNAL_CONT_RESP_DET_SK] [numeric] (15, 0) NOT NULL
)
GO
ALTER TABLE [sascdmp].[CI_EXTERNAL_RESPONSE] ADD CONSTRAINT [EXTERNAL_RESPONSE_PK] PRIMARY KEY CLUSTERED  ([EXTERNAL_RESPONSE_SK])
GO
ALTER TABLE [sascdmp].[CI_EXTERNAL_RESPONSE] ADD CONSTRAINT [EXTERNAL_RESPONSE_FK1] FOREIGN KEY ([EXTERNAL_CONT_RESP_DET_SK]) REFERENCES [sascdmp].[CI_EXTERNAL_CONT_RESP_DETAIL] ([EXTERNAL_CONT_RESP_DET_SK])
GO
