CREATE TABLE [sascdmp].[CI_COMMUNICATION_EXT]
(
[COMMUNICATION_SK] [numeric] (15, 0) NOT NULL,
[MARKETING_COST] [numeric] (14, 2) NULL
)
GO
ALTER TABLE [sascdmp].[CI_COMMUNICATION_EXT] ADD CONSTRAINT [COMM_EXT_PK] PRIMARY KEY CLUSTERED  ([COMMUNICATION_SK])
GO
ALTER TABLE [sascdmp].[CI_COMMUNICATION_EXT] ADD CONSTRAINT [COMM_EXT_FK1] FOREIGN KEY ([COMMUNICATION_SK]) REFERENCES [sascdmp].[CI_COMMUNICATION] ([COMMUNICATION_SK])
GO
