CREATE TABLE [sascdmp].[CI_CAMPAIGN_TYPE]
(
[CAMPAIGN_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CAMPAIGN_TYPE_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdmp].[CI_CAMPAIGN_TYPE] ADD CONSTRAINT [CAMP_TYPE_PK] PRIMARY KEY CLUSTERED  ([CAMPAIGN_TYPE_CD])
GO
