CREATE TABLE [sascdmp].[CI_CTL_GRP_CELL_X_TEST_CELL]
(
[CONTROL_GROUP_CELL_SK] [numeric] (15, 0) NOT NULL,
[MARKETING_CELL_SK] [numeric] (15, 0) NOT NULL
)
GO
ALTER TABLE [sascdmp].[CI_CTL_GRP_CELL_X_TEST_CELL] ADD CONSTRAINT [CGC_X_TST_CELL_PK] PRIMARY KEY CLUSTERED  ([CONTROL_GROUP_CELL_SK], [MARKETING_CELL_SK])
GO
ALTER TABLE [sascdmp].[CI_CTL_GRP_CELL_X_TEST_CELL] ADD CONSTRAINT [CGC_X_TST_CELL_FK1] FOREIGN KEY ([MARKETING_CELL_SK]) REFERENCES [sascdmp].[CI_MARKETING_CELL] ([MARKETING_CELL_SK])
GO
ALTER TABLE [sascdmp].[CI_CTL_GRP_CELL_X_TEST_CELL] ADD CONSTRAINT [CGC_X_TST_CELL_FK2] FOREIGN KEY ([CONTROL_GROUP_CELL_SK]) REFERENCES [sascdmp].[CI_MARKETING_CELL] ([MARKETING_CELL_SK])
GO
