CREATE TABLE [sascdm].[CI_CONTACT_RULE]
(
[CONTACT_RULE_SK] [numeric] (15, 0) NOT NULL,
[CONTACT_RULE_NM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TREATMENT_SK] [numeric] (15, 0) NULL,
[CONTACT_RULE_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_RULE_INTERVAL_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_RULE_PERIOD] [numeric] (10, 0) NULL,
[CONTACT_RULE_FREQUENCY] [numeric] (10, 0) NULL,
[CHANNEL_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_CONTACT_RULE] ADD CONSTRAINT [CONT_RULE_PK] PRIMARY KEY CLUSTERED  ([CONTACT_RULE_SK])
GO
ALTER TABLE [sascdm].[CI_CONTACT_RULE] ADD CONSTRAINT [CONT_RULE_FK1] FOREIGN KEY ([CONTACT_RULE_TYPE_CD]) REFERENCES [sascdm].[CI_CONTACT_RULE_TYPE] ([CONTACT_RULE_TYPE_CD])
GO
ALTER TABLE [sascdm].[CI_CONTACT_RULE] ADD CONSTRAINT [CONT_RULE_FK2] FOREIGN KEY ([CONTACT_RULE_INTERVAL_CD]) REFERENCES [sascdm].[CI_CONTACT_RULE_INTERVAL] ([CONTACT_RULE_INTERVAL_CD])
GO
