CREATE TABLE [sascdmp].[CI_RESPONSE_HISTORY]
(
[CELL_PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[TREATMENT_SK] [numeric] (15, 0) NOT NULL,
[TREATMENT_HASH_VAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RESPONSE_SK] [numeric] (15, 0) NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RESPONSE_DTTM] [datetime] NOT NULL,
[RESPONSE_DT] [date] NULL,
[RESPONSE_CHANNEL_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INFERRED_RESPONSE_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESPONSE_VALUE_AMT] [numeric] (14, 2) NULL,
[EXTERNAL_RESPONSE_INFO_ID1] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTERNAL_RESPONSE_INFO_ID2] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESPONSE_TRACKING_CD] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESSED_DTTM] [datetime] NULL
)
GO
ALTER TABLE [sascdmp].[CI_RESPONSE_HISTORY] ADD CONSTRAINT [RESP_HIST_PK] PRIMARY KEY CLUSTERED  ([CELL_PACKAGE_SK], [TREATMENT_SK], [TREATMENT_HASH_VAL], [RESPONSE_SK], [SSB_CRMSYSTEM_CONTACT_ID], [RESPONSE_DTTM])
GO
