CREATE TABLE [sascdm].[CI_CONTACT_HISTORY_STATUS]
(
[CONTACT_HISTORY_STATUS_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTACT_HISTORY_STATUS_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [sascdm].[CI_CONTACT_HISTORY_STATUS] ADD CONSTRAINT [CONT_HIST_STAT_PK] PRIMARY KEY CLUSTERED  ([CONTACT_HISTORY_STATUS_CD])
GO
