CREATE TABLE [sasload].[CH49BAC4CB9461C0647811C_001]
(
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CELL_PACKAGE_SK] [numeric] (15, 0) NOT NULL,
[RESPONSE_TRACKING_CD] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHSTATUS_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PACKAGE_HASH_VAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPTIMIZATION_BACKFILL_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT_DTTM] [datetime] NOT NULL,
[CONTACT_DT] [date] NULL
)
GO
