CREATE TABLE [src].[TI_PatronMDM]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NULL,
[Patron] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerType] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryAddressType] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryAddressStreet] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryAddressCity] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryAddressState] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryAddressZipCode] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryAddressCountry] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2Type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2Street] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2City] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2State] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2ZipCode] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2Country] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3Type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3Street] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3City] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3State] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3ZipCode] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3Country] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address4Type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address4Street] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address4City] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address4State] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address4ZipCode] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address4Country] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address5Type] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address5Street] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address5City] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address5State] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address5ZipCode] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address5Country] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CellPhone] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessPhone] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhoneType] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EvEmail] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonalEmail] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessEmail] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherEmailType] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherEmail] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorID] [int] NULL,
[PatronStatusCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatronStatus] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VIP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Level] [int] NULL,
[Donor_Type] [int] NULL,
[internet_profile] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTRIBUTE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTE] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTERNAL_NUMBER] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIN] [bigint] NULL,
[TAG] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Comments] [int] NULL,
[comments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PacCreateDate] [datetime] NULL,
[UpdatedDate] [datetime] NULL,
[SAL_F] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAL_N1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorityPtsTix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerTypeCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [src].[TI_PatronMDM] ADD CONSTRAINT [PK_TI_PatronMDM_ETL_ID] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
