CREATE TABLE [stg].[Neulion_Contact]
(
[MemberID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStatus] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Count] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChapterName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistrictAbbr] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DavieID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryContact] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorStatus] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearsReceivedYACredit] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HighestGivingLevelRequirement] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employer] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MatchingGiftRatio] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MatchMin] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MatchMax] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearstheDonorHasUpgraded] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearstheDonorHasDowngraded] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearstheDonorHasGiven110Percent] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SRYears] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousTypesofPayment] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearsasStudentRam] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFSignUp] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMGStaffMember] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMGSignup] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorStatusModDate] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferralMemberID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateofBirth] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActiveDate] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastLoginDate] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberofCourtsidePassesMB] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberofPeeblesPassesMB] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateJoined] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF16] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF15] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF14] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF13] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF12] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF11] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DQAF10] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndowedScholarships] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEProspectRating] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WENetWorth] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEGiftCapacityRange] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbilitecID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbilitecIDDuplicate?] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleInit] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameSuffix] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseTitle] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillAddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillCity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillStateProv] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillZipCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillCountry] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessPhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bus Ext] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CellPhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConsecutiveYearsGiving] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalYearsGiving] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name Phone EmailModDate] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentContactChangeDate] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysSinceAccount AddrChange] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysSincePoints Level Status] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExecBoard] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BoardAdvisors] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PastPresident] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BoardofTrustees] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BigHitter] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysSinceCustomDataChange] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
