IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB CRM Sec')
CREATE LOGIN [SSBINFO\SSB CRM Sec] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB CRM Sec] FOR LOGIN [SSBINFO\SSB CRM Sec]
GO
