IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB ETL Sec')
CREATE LOGIN [SSBINFO\SSB ETL Sec] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB ETL Sec] FOR LOGIN [SSBINFO\SSB ETL Sec]
GO
