IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB MDM Sec')
CREATE LOGIN [SSBINFO\SSB MDM Sec] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB MDM Sec] FOR LOGIN [SSBINFO\SSB MDM Sec]
GO
