CREATE SCHEMA [crmdev]
AUTHORIZATION [ssb_ksniffin]
GO
GRANT ALTER ON SCHEMA:: [crmdev] TO [BBCRM]
GO
GRANT CONTROL ON SCHEMA:: [crmdev] TO [BBCRM]
GO
GRANT CREATE SEQUENCE ON SCHEMA:: [crmdev] TO [BBCRM]
GO
GRANT DELETE ON SCHEMA:: [crmdev] TO [BBCRM]
GO
GRANT EXECUTE ON SCHEMA:: [crmdev] TO [BBCRM]
GO
GRANT INSERT ON SCHEMA:: [crmdev] TO [BBCRM]
GO
GRANT SELECT ON SCHEMA:: [crmdev] TO [BBCRM]
GO
GRANT UPDATE ON SCHEMA:: [crmdev] TO [BBCRM]
GO
